# Setup
title: SmnTin's bay
url: https://smntin.github.io
paginate: 10
paginate_path: "/blog/page-:num/"
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-email-protect
  - jekyll-feed

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Semyon Panenkov
  url: https://github.com/SmnTin

feed:
  posts_limit: 256
  
# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Blog
    url: /blog
  - title: Atom
    url: /atom.xml

# Collections like projects and posts
collections:
  - projects

rouge:
  theme: github

giscus:
  repo:                "SmnTin/smntin.github.io"
  repo-id:             "R_kgDOJ1mn6A"
  category:            "Comments"
  category-id:         "DIC_kwDOJ1mn6M4CeM9v"
  reactions-enabled:   "1"
  theme:               "dark_dimmed"

google_site_verification:
  78jAi9YYcWfWMqrXrAfW_maK4W3fwVxntFI12LwE7WI

defaults:
  # Don't include documents in assets in the sitemap
  - scope:
      path: assets/**
    values:
      sitemap: false

  # Enable comments on all posts
  - scope:
      type: posts
    values:
      comments: true

